//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public string MaCC { get; set; }
        public string MaNV { get; set; }
        public string MaCH { get; set; }
        public string Ngay { get; set; }
        public string SoGioLam { get; set; }
        public Nullable<int> TangCa { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
