//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public ChucVu()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaCV { get; set; }
        public string TenChucVu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
