//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKhuyenMai
    {
        public int MaCTKM { get; set; }
        public Nullable<int> MaKM { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string GiamGia { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
