//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuXuat
    {
        public int MaCTPX { get; set; }
        public Nullable<int> MaPX { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string MaSize { get; set; }
        public Nullable<int> MaMau { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
