//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public CuaHang()
        {
            this.CTSanPhams = new HashSet<CTSanPham>();
            this.HoaDons = new HashSet<HoaDon>();
            this.NhanViens = new HashSet<NhanVien>();
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public int MaCH { get; set; }
        public string TenCH { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CTSanPham> CTSanPhams { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
    }
}
