//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string NgayLap { get; set; }
        public Nullable<int> MaCH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
