//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public KhuyenMai()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.CTKhuyenMais = new HashSet<CTKhuyenMai>();
        }
    
        public int MaKM { get; set; }
        public string TenKM { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual ICollection<CTKhuyenMai> CTKhuyenMais { get; set; }
    }
}
