//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.CTPhieuXuats = new HashSet<CTPhieuXuat>();
        }
    
        public int MaPX { get; set; }
        public string NgayLap { get; set; }
        public Nullable<int> ThanhToan { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaCH { get; set; }
        public string TrinhTrang { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CTPhieuXuat> CTPhieuXuats { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
