//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.CTKhuyenMais = new HashSet<CTKhuyenMai>();
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
            this.CTPhieuXuats = new HashSet<CTPhieuXuat>();
            this.CTSanPhams = new HashSet<CTSanPham>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public string MoTa { get; set; }
        public string ThongTin { get; set; }
        public string HinhAnh { get; set; }
        public string GioTinh { get; set; }
        public string Moi { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual ICollection<CTKhuyenMai> CTKhuyenMais { get; set; }
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual ICollection<CTPhieuXuat> CTPhieuXuats { get; set; }
        public virtual ICollection<CTSanPham> CTSanPhams { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
