//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public string MaCC { get; set; }
        public string MaNV { get; set; }
        public string Ngay { get; set; }
        public string SoGioLam { get; set; }
        public string TrangThaiChamCong { get; set; }
        public string TrangThai { get; set; }
        public string TangCa { get; set; }
    }
}
