//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public string MaCTHD { get; set; }
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public string MaSize { get; set; }
        public string MaMau { get; set; }
        public string MaCH { get; set; }
        public string GiaBan { get; set; }
        public string SoLuong { get; set; }
        public string MaKM { get; set; }
        public string TrangThai { get; set; }
    }
}
