//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKhuyenMai
    {
        public string MaKM { get; set; }
        public string MaSP { get; set; }
        public string MaCH { get; set; }
        public string GiamGia { get; set; }
        public string MaKH { get; set; }
        public string MaCTKM { get; set; }
        public string TrangThai { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
