//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhap
    {
        public string MaCTPN { get; set; }
        public string MaPN { get; set; }
        public string MaSP { get; set; }
        public string MaSize { get; set; }
        public string MaMau { get; set; }
        public string SoLuong { get; set; }
        public string GiaNhap { get; set; }
        public string ChiecKhau { get; set; }
        public string TrangThai { get; set; }
    }
}
