//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public string NgayLap { get; set; }
        public string MaKH { get; set; }
        public string TongTien { get; set; }
        public string TrangThai { get; set; }
        public string MaCH { get; set; }
    }
}
