//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongNhanVien
    {
        public string MaLuong { get; set; }
        public string MaNV { get; set; }
        public string LuongCoBan { get; set; }
        public string SoNgayLam { get; set; }
        public string TangCa { get; set; }
        public string ThamNien { get; set; }
        public string PhuCap { get; set; }
        public string Thuong { get; set; }
        public string TienLanh { get; set; }
        public string LuongPartTime { get; set; }
        public string SoGiolam { get; set; }
        public string TrangThai { get; set; }
        public string Ngay { get; set; }
    }
}
