//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DonGia { get; set; }
        public string MaLoai { get; set; }
        public string GiaNhap { get; set; }
        public string SoLuongTon { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string MaCH { get; set; }
        public string TrangThai { get; set; }
    }
}
