//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public string MaSize { get; set; }
        public string TenSize { get; set; }
        public string CanNang { get; set; }
        public string TrangThai { get; set; }
    }
}
